name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - uses: actions/cache@v1
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-dart-cache-${{ env.flutter_version }}
          restore-keys: |
            ${{ runner.OS }}-dart-cache-

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze --fatal-infos

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [stable, beta, dev]

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{ matrix.sdk }}

      - uses: actions/cache@v1
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-dart-cache-${{ env.flutter_version }}
          restore-keys: |
            ${{ runner.OS }}-dart-cache-

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test
